### ISSUE TITLE
A problem on dataset

### ISSUE THREAD

**Issue by ZhongQiangDev** [h31nr1ch/TeamUFPR-IDPT2021#1]
I have a problem on dataset: you said "To run the code, use the following command: python3 main.py --dataset-train ../dataset/Training/training_tweets.csv --dataset-test ../dataset/Test/test_tweets.csv ", but I dont find csv files in this repository. Did you forget to upload the dataset? I am looking for IDPT2021 dataset. o(╥﹏╥)o

**Comment by h31nr1ch** [comment]
Hi @ZhongQiangDev, the dataset is a closed source, and I cannot make it available without the permission of the owners.

But as far as I can remember from the competition the dataset is to be used for academic purposes. I recommend you take a look at the page on IDPT2021 [here](https://sites.google.com/inf.ufpel.edu.br/idpt2021/data)

and send an email to (idpt2021@inf.ufpel.edu.br) requesting the dataset password.

If not successful. Larissa Freitas was organizing the competition, it might be worth sending her an email (larissa@inf.ufpel.edu.br).

Another option would be to send an email to a coauthor of the work. Here is a link to the article published by the group at the time [here](https://rua.ua.es/dspace/bitstream/10045/117496/1/PLN_67_23.pdf).

Sorry about that, but as I'm not the owner of the dataset, I can't make it public :/

**Comment by ZhongQiangDev** [comment]
Thanks a lot for your answer. Your answer helped me very well.
